### PR TITLE
Display uncompressed document size in UI

### PR DESCRIPTION
**Pull request by evanxg852000**
Closes https://github.com/quickwit-oss/quickwit/issues/3320

Reordered display and added  `Size of published documents`
Screenshot from 2023-05-16 16-44-09

updated label
Screenshot from 2023-05-21 07-28-06

### CODE REVIEW

**Comment by guilload** [comment]
Would `Size of published documents (uncompressed)` be less confusing?

**Review by fmassot — APPROVED** [review]

**Comment by fmassot** [comment]
@evanxg852000 can you rename also the corresponding field in `IndexStats`?

**Comment by evanxg852000** [comment]
@fmassot I renamed and added both size (published docs, publish uncompressed doc) would be nice to have a look.

**Review by fmassot — APPROVED** [review]
LGTM. Can you update the REST API docs too?

**Pull request merged**
