### PR TITLE
fix time format

### LINKED ISSUE #1203: "Indexed in <float> min"
After ingest via the cli we display a duration with a silly format.

```Indexed 5032105 documents in 7.38min.```

That's not how humans like to read time. Also adding thousands separator would be nice for the number of docs.

```Indexed 5,032,105 documents in 7 min 23 secs.```

would be nicer.

### PR DESCRIPTION
**Pull request by dai-dao**
### Description
Saw this issue when i was browsing discord, anyways was a quick fix so I made this pr :+1: 

Closes #1203

### How was this PR tested?
Describe how you tested this PR.

### CODE REVIEW

**Review by fulmicoton — APPROVED** [review]

**Review by fulmicoton — CHANGES_REQUESTED** [review]
Can you fix the formatting of the number of documents too?

**Review by fulmicoton — CHANGES_REQUESTED** [review]
The PR is not linked to the issue in any way. Ideally, the commit message should contain
`Closes #1203` , so that the issue is both referenced and gets automatically closes as the PR is merged.

**Comment by fulmicoton** [comment]
@dai-dao We can afford adding a deps to humantime and num-formats I think.

**Comment by dai-dao** [comment]
yea humantime has a few dependencies, really nice to use :+1:

**Review by fulmicoton — APPROVED** [review]

**Pull request merged**
