### PR TITLE
1099 cli ingest cleanup cache

### LINKED ISSUE #1099: ingest cli leaves us with splits in cache
The ingest CLI gives a little bit of a misleading experience.
We keep the split in the split cache after the ingestion has terminated.

Maybe we should add a CLI option to force a cleanup?

### PR DESCRIPTION
**Pull request by dai-dao**
### Description
just a small doc update for --clean_cache ingest cli

### How was this PR tested?
Describe how you tested this PR.

closes #1099

### CODE REVIEW

**Comment by dai-dao** [comment]
@PSeitz just added an update to the doc for the --clean_cache option. Cheers

**Comment by PSeitz** [comment]
Nice catch, did you use the doc generation tool? https://github.com/quickwit-oss/quickwit/blob/8d9a1a1a661ca096b74a81c3af5eb7a0ecc96742/CONTRIBUTING.md#generating-the-cli-docs

**Comment by dai-dao** [comment]
Thanks, i ran the script to generate `cli_insert.md` and then manually edit the `cli.md`

**Comment by PSeitz** [comment]
I think the `docs/reference/cli_insert.md` should not be committed

**Comment by dai-dao** [comment]
ok i removed cli_insert.md

**Comment by guilload** [comment]
I've renamed the option and updated the documentation as part of #1271. Closing.

**Pull request closed without merging**
