### PR TITLE
Add integration test for doc mapper update

### PR DESCRIPTION
**Pull request by rdettai**
### Description

Add some high level validation that searches still work after doc mapper update. 

It would be interesting to do the same with aggregations.

Part of https://github.com/quickwit-oss/quickwit/issues/5084

### How was this PR tested?

NA (these are tests)

### CODE REVIEW

**Review by rdettai — COMMENTED** [review]
Any juicy scenario suggestion is welcome

**Comment by trinity-1686a** [comment]
ideas of test i've run with various level of success:
- u64 -> string, verify the field is still present after update (initially broken, fixed by #5076)
- with dynamic mode: create index without field1, ingest data with field1, create that field1, ingest some more. Check we can search for both before and after.
- with strict mode: create index without a field1, ingest docs without field1, create field1, ingest data with this field. Check we don't get error from old splits because of searching on unknown field
- index string with `raw` tokenizer no position; ingest document containing `-` (dash) in value, such as `roller-coaster`. update tokenizer to default, with positions. ingest more documents. make a phrase query for that doc (this is expected to work)
- index string with `default` tokenizer no position; ingest document with `-` (dash) in value. update to enable positions. ingest more documents. make a phrase query for that doc. this one should work in the future, but is expected to fail currently

**Comment by rdettai** [comment]
> u64 -> string, verify the field is still present after update 

Not sure I get this one. If the search on the field goes through, it necessarily means that the field is still present, no?

**Comment by rdettai** [comment]
@trinity-1686a I added all your test scnarii

Because of your suggestion to test "u64 -> string, verify the field is still present after update", I changed the assert from just the number of hits to the whole hit content. I got 2 surprising results:
- `test_update_doc_mapping_json_to_object`: I update a json type to an explicit object type, and the fields are dropped in the resulting hit.
- `test_update_doc_mapping_strict_to_dynamic`: I switch from an explicit (strict) schema to a dynamic one, and the fields are dropped in the resulting hit.

**Comment by trinity-1686a** [comment]
that's interesting, can you add these test as disabled, and i'll try to make them pass

**Comment by rdettai** [comment]
done

**Review by trinity-1686a — APPROVED** [review]

**Pull request merged**
