### PR TITLE
Updated readme: UI & content

### PR DESCRIPTION
**Pull request by maximkpa**
Updated readme: UI & content

### CODE REVIEW

**Comment by fmassot** [comment]
@fulmicoton Almost good, can you check if there is no blunder in it?

**Comment by evanxg852000** [comment]
@maximkpa @fmassot  Please, Can we have a screenshot of the search UI with the browser frame around the screenshot seems to be cut off though it's not. 
Something like this with transparent background

**Comment by fmassot** [comment]
@evanxg852000 good point, we can definitely improve this.

**Comment by fmassot** [comment]
we plan to make a small video / gif, so we might skip the browser frame part.

**Pull request merged**
