### PR TITLE
Add an option to force or wait for commit

### PR DESCRIPTION
**Pull request by imotov**
### Description

Adds an option to force a commit or wait for the next commit while issuing an ingest command. This commit only implements it for the ingest endpoint. If all records in the batch fail, the command will hang until at least one good document is indexed until #2826 is merged in or the document parsing is moved to the early stages.

See #2699

### How was this PR tested?

Added tests.

### CODE REVIEW

**Comment by fulmicoton** [comment]
@trinity-1686a can you have a look?

**Review by trinity-1686a — COMMENTED** [review]
It would be nice to have an e2e style integration test that ingest a few docs forcing commit and immediately search for them, but that'll possibly be best done once #2984 has been worked on

**Review by trinity-1686a — APPROVED** [review]

**Comment by fmassot** [comment]
Let's wait for 0.5 release before merging.

**Comment by imotov** [comment]
As much as release branches can be a pain, the balance of cost vs benefit of having them will only move towards the benefit as the team and customer base grow. Maybe be something to consider for 0.6?

**Comment by fmassot** [comment]
@imotov absolutely, we are releasing tomorrow so we can merge your PR tomorrow.

**Pull request merged**
