### PR TITLE
update tantivy

### PR DESCRIPTION
**Pull request by PSeitz**
### Description

Describe the proposed changes made in this PR.

### How was this PR tested?

Describe how you tested this PR.

### CODE REVIEW

**Comment by fmassot** [comment]
@PSeitz is there a breaking change?

**Comment by PSeitz** [comment]
> @PSeitz is there a breaking change?

Yes, u128 fast fields won't work anymore

**Comment by fmassot** [comment]
ok, not a problem on my use case :D

**Comment by fulmicoton** [comment]
thx.
@trinity-1686a, FYI Pascal updated tantivy.

**Pull request merged**
