### PR TITLE
Rename SplitMetadata.size_in_bytes

### PR DESCRIPTION
**Pull request by evanxg852000**
Renamed `SplitMetadata.size_in_bytes` to `original_size_in_bytes` to avoid confusion

Closes https://github.com/quickwit-oss/quickwit/issues/1667

### CODE REVIEW

**Comment by guilload** [comment]
I find that `original_size_in_bytes` is merely an improvement. What about something like `uncompressed_payload_size_in_bytes`?

**Comment by evanxg852000** [comment]
Yes @guilload  I still found it confusing but I wanted to conform to a previous renaming thinking this was what we wanted after all. I had these names in mind  too `ingested_docs_size_in_bytes` `original_docs_size_in_bytes`. so let's decide here.

**Comment by PSeitz** [comment]
I'm in favor of `original_docs_size_in_bytes` or `uncompressed_docs_size_in_bytes`

**Comment by evanxg852000** [comment]
@guilload  any take on this? I am leaning towards `original_docs_size_in_bytes`

**Comment by guilload** [comment]
Good suggestion, @PSeitz. I'm leaning towards `uncompressed_docs_size_in_bytes` or `raw_docs_size_in_bytes`. Original makes perfect sense for us, Quickwit devs, but I'm afraid that might not be explicit enough for newcomers.

**Comment by evanxg852000** [comment]
@guilload @PSeitz  I finally settled with `raw_docs_size_in_bytes`. It's shorter IMO

**Pull request merged**
