### PR TITLE
fix: duplicate splits planned on pipeline crash-respawn

### PR DESCRIPTION
**Pull request by dojiong**
### Description

MergePlanner will plan the same splits to downstream when MergePipeline crash-then-respawn.

The reason is that MergePlanner fetched all the splits from metastore, these splits maybe duplicated with the NewSplits message in mailbox.

*This fix is unfinished*

### CODE REVIEW

**Comment by fulmicoton** [comment]
Attempts to fix #3847

**Comment by fulmicoton** [comment]
Awesome. If I understand correctly this fix should address most of our problem... Except there is still the (rare) possibility that we had a PlanMerge message in our mailbox.

**Comment by dojiong** [comment]
> Except there is still the (rare) possibility that we had a PlanMerge message in our mailbox.

Right! I dont have a better solution, so I changed it to draft.

one not good but works: add a field to PlanMerge to indicate a bootstrap PlanMerge, merge-planner reject all the PlanMerge before a bootstrap PlanMerge received

**Comment by fmassot** [comment]
Indeed, it should help.

In the current implementation, we cannot have duplicated splits in the merge planner thanks to [this condition](https://github.com/quickwit-oss/quickwit/blob/8baf1ec702bd60a2dd7edad4925d173691c03419/quickwit/quickwit-indexing/src/actors/merge_planner.rs#L160-L167).

But... if we plan merges, we send splits in the pipeline, and they are removed from the merge planner.... so the above condition is insufficient to prevent duplicated splits in the whole merge pipeline.

We could enhance the condition by checking that the new split is not the ongoing merge operations tracked in `ongoing_merge_operations_inventory`.

**Review by fulmicoton — APPROVED** [review]

**Comment by dojiong** [comment]
I think this should cover all the scenarios, I'll try on my production cluster.

**Comment by fulmicoton** [comment]
I think the scenario cannot really happen today due to a technicality: the message queue of the merge planner have a capacity of 1 :).

**Comment by fulmicoton** [comment]
If there are no objections I'll merge this!

**Review by fulmicoton — APPROVED** [review]

**Comment by dojiong** [comment]
> the message queue of the merge planner have a capacity of 1 :).
The merge-publisher may await on sending NewSplits to merge-planner, so the capacity of 1 or 100 is not matter.

Is this possible?
1. merge-publisher send NewSplits to merge-planner, used the capacity of merge-planner's mailbox
2. merge-publisher send NewSplits to merge-planner, no capacity available, current future wait mailbox available
3. merge-pipeline crashed
4. merge-pipeline respawn, fetch all the splits from metastore
5. new merge-planner send PlanMerge to self, will fail (mailbox is full)
6. merge-planner received NewSplits from step-1, make a new plan includes splits from step-4
7. merge-planner received NewSplits from step-2, make a new plan includes splits from step-1/2, **splits duplicated**

I got a new `deletable error` after this patch @fulmicoton

**Pull request merged**
