### PR TITLE
Feature: [Dev Experience] Add dev container configuration for GitHub Codespaces

### LINKED ISSUE #4163: [Dev Experience] Add dev container configuration for GitHub Codespaces
## Motivation

 I would like to propose adding a dev container configuration for GitHub Codespaces. This would make it easier for developers to set up their environment and work on the project without much hassle and effort. Setting up the project for the first time requires CMake, Docker, node, yarn, awslocal protoc and other tools. However, installing and configuring these tools manually can be time-consuming and error-prone, especially for new contributors or low-end machines. 

## Solution

 It would be nice to have a dev container configuration for GitHub Codespaces that would automate the setup of the development environment and provide a consistent and reproducible experience. This would make contributing to the project easier as it would:
 
- Lower the barrier to entry for new contributors due to the ability to quickly spin up a fully set up environment and focus on making a contribution instead of spending hours trying to get the right version of some tool installed. 

## Tasks to make this happen

- [x] Add dev Container configuration
- [ ] Update `README.md` and `CONTRIBUTING.md` to include information on how to get started with a codespace

### PR DESCRIPTION
**Pull request by unpervertedkid**
### Description

Fixes #4163 

#### Motivation

 I would like to propose adding a dev container configuration for GitHub Codespaces. This would make it easier for developers to set up their environment and work on the project without much hassle and effort. Setting up the project for the first time requires CMake, Docker, node, yarn, awslocal protoc and other tools. However, installing and configuring these tools manually can be time-consuming and error-prone, especially for new contributors or low-end machines. 

#### Solution

 It would be nice to have a dev container configuration for GitHub Codespaces that would automate the setup of the development environment and provide a consistent and reproducible experience. This would make contributing to the project easier as it would:
 
- Lower the barrier to entry for new contributors due to the ability to quickly spin up a fully set up environment and focus on making a contribution instead of spending hours trying to get the right version of some tool installed. 

#### Tasks to make this happen

- [x] Add dev Container configuration
- [ ] Update `README.md` and `CONTRIBUTING.md` to include information on how to get started with a codespace

### How was this PR tested?

This Pr was testing by:
-  Creating a GitHub codespace using the generated devcontainer configuration and checking that all the required tools were set up successfully. 
- Running the common commands that a contributor will be expected to run and confirming that they worked.

### CODE REVIEW

**Comment by unpervertedkid** [comment]
@fulmicoton Please take a look

**Comment by fmassot** [comment]
thanks a lot @unpervertedkid

I tested it and it worked well, the dev UX is really really nice. I saw 3 issues:
- the disk space is small, I did a cargo build and make test-all and run out of disk space
- I got errors in some tests, I'm unsure if it was related to the disk space or not, I will rerun the test suite on a new codespace
- the price but it's not related to your code.

Overall, I'm good with your PR. @guilload do you want to check the content?

**Comment by unpervertedkid** [comment]
@fmassot The disk space for codespaces is limited for freee codespaces but if one has access to paid codespace they can then configure a codespace with more disk but for the mean time I set the minimum requirements to be the maximum disk and compute space for the free codespace configuration.

Let me try to recreate the errors you ran into and try to figure out what the issue could be. I will also try and look into caching but I would want to get this PR in and then I can open another PR to work on that.

**Comment by guilload** [comment]
Looks good to me!

**Review by guilload — APPROVED** [review]

**Comment by unpervertedkid** [comment]
> * The price is not related to your code: quickwit takes time to compile so we need a lot of compute, it would be nice to be able to do so some caching there.

Hi @fmassot, I was thinking about your suggestion to use caching to speed up the compilation. I think it’s a great idea and I would love to work on it. My first thought was to use [sccache](https://github.com/mozilla/sccache), a distributed compiler cache for Rust. Do you think that would be a good solution? If so, could you please create an issue with a clear guide on what we should cover, and I will pick it up then. Thank you!

**Pull request merged**
