### PR TITLE
Moved tutorials into geting-started

### PR DESCRIPTION
**Pull request by evanxg852000**
Closes https://github.com/quickwit-oss/quickwit/issues/2630

### CODE REVIEW

**Comment by fmassot** [comment]
Capture d’écran 2023-01-18 à 14 31 06
Capture d’écran 2023-01-18 à 15 00 09

**Comment by fmassot** [comment]
@guilload friendly ping. I will also replace "Ingesting" by "Ingest" to keep all verbs without "ing", I'm happier with short title.

**Comment by evanxg852000** [comment]
LGTM, @fmassot  indeed shorter texts in the menu are better.

**Review by fmassot — COMMENTED** [review]
LGTM

**Pull request merged**
