### PR TITLE
Add GET api/v1/indexes to Lambda searcher

### LINKED ISSUE #5039: Add `GET api/v1/indexes` to Lambda searcher
**Is your feature request related to a problem? Please describe.**
To use the Lambda distribution as Grafana datasource, we need the `GET api/v1/indexes` endpoint

**Describe the solution you'd like**
Expose it like the search and elasticsearch endpoints

**Describe alternatives you've considered**
NA

**Additional context**
It is worth noting that this change is required for the Grafana datasource to work, but there might be other (currently unidentified) requirements.

### PR DESCRIPTION
**Pull request by tyrwzl**
### Description

Closes #5039.
Add `GET /api/v1/indexes` endpoint to Lambda Searcher to use quickwit Lambda as Grafana datasource.

### How was this PR tested?

1. Locally running Lambda searcher by using cargo lambda.
```
export AWS_ACCESS_KEY_ID="****"
export AWS_SECRET_ACCESS_KEY="****"
export AWS_SESSION_TOKEN="****"
export AWS_REGION="us-east-1"
export AWS_LAMBDA_HTTP_IGNORE_STAGE_IN_PATH="true"
export QW_LAMBDA_INDEX_BUCKET="quickwitlambdastack-quickwitindexstore****"
export QW_LAMBDA_INDEX_ID="hdfs-logs"
export QW_LAMBDA_METASTORE_BUCKET="quickwitlambdastack-quickwitindexstore****"
export RUST_LOG="quickwit=info"
cargo lambda watch
```

2. Setup Grafana (https://quickwit.io/docs/get-started/tutorials/trace-analytics-with-grafana)
	- url: `http://host.docker.internal:9000/lambda-url/searcher/api/v1`
	- Index ID: `hdfs-logs`

Screenshot 2024-06-03 at 20 29 44

3. Explorer quickwit data
Screenshot 2024-06-03 at 20 32 25

### CODE REVIEW

**Review by rdettai — APPROVED** [review]
Thanks for this contribution and for testing it on Grafana! It's amazing to see it works! 

Nit: have you tried running the CDK examples already? If so, you could add this new endpoint to the tests here https://github.com/quickwit-oss/quickwit/blob/f8590d5f6ec9db7be9ccb4357d34c4b20a444ec0/distribution/lambda/cdk/cli.py#L420-L462. These are some sanity checks on the end to end CDK deployment. You can run them by first deploying the stack:

```
export CDK_ACCOUNT=123456789
export CDK_REGION=us-east-1
make bootstrap
make deploy-mock-data
make test-mock-data-endpoints
```

**Comment by tyrwzl** [comment]
Thank you for instructions.
Added `GET api/v1/indexes` test.

```
GET /api/v1/mock-sales/search?query=animal
[200] => {"num_hits": 0, "hits": [], "elapsed_time_micros": 51301, "errors": []}
POST /api/v1/mock-sales/search
[200] => {"num_hits": 0, "hits": [], "elapsed_time_micros": 1600, "errors": []}
GET /api/v1/_elastic/mock-sales/_search?q=animal
[200] => {"took": 1, "timed_out": false, "_shards": {"total": 1, "successful": 1, "skipped": 0, "failed": 0},
POST /api/v1/_elastic/mock-sales/_search
[200] => {"took": 1, "timed_out": false, "_shards": {"total": 1, "successful": 1, "skipped": 0, "failed": 0},
GET /api/v1/_elastic/mock-sales/_field_caps?fields=quantity
[200] => {"indices": [], "fields": {}}
GET /api/v1/_elastic/mock-sales/_search?query=animal
[400] => {"message": "unknown field `query`, expected one of `_source`, `_source_excludes`, `_source_includes
GET /api/v1/_elastic/_search?q=animal
[501] => {"message": "_elastic/_search is not supported yet. Please try the index search endpoint (_elastic/{
GET /api/v1/indexes/mock-sales
[200] => {"version": "0.8", "index_uid": "mock-sales:01HZGCF383DMRQMFNEHPWFWB0S", "index_config": {"version":
```

**Comment by rdettai** [comment]
@tyrwzl we should add some instructions on how to set up Grafana on top of the API Gateway in the [README](https://github.com/quickwit-oss/quickwit/blob/f8590d5f6ec9db7be9ccb4357d34c4b20a444ec0/distribution/lambda/README.md).

**Comment by tyrwzl** [comment]
@rdettai 
Sure, I'll work on that.

**Comment by tyrwzl** [comment]
@rdettai 
Hi, I created PR #5092.
Could you please take a look at it?

**Pull request merged**
