### PR TITLE
ISSUE-1086 Check query against latest schema - root streaming

### PR DESCRIPTION
**Pull request by linxGnu**

### CODE REVIEW

**Comment by fulmicoton** [comment]
Awesome! I made a lot of change following our discussion on the other ticket. Could you rebase?

**Review by fulmicoton — APPROVED** [review]

**Comment by linxGnu** [comment]
@fulmicoton I have rebased on your recent changes. PTAL

**Review by fulmicoton — APPROVED** [review]

**Comment by fulmicoton** [comment]
Thank you!

**Comment by fulmicoton** [comment]
I move the repo to quickwit-oss. I wonder if you need to resign the CLA?

**Comment by linxGnu** [comment]
Oh, it looks to me that I don't need to resign. I don't know :cry: 

Screenshot from 2022-01-27 14-41-25

**Comment by fulmicoton** [comment]
@linxGnu Let me check it is probably a permission on our side then.

**Comment by fulmicoton** [comment]
(closing and reopening in the hope to get another request to license/cla)

**Comment by fulmicoton** [comment]
For the record:
I had to readd permission from cla-assistant to the new organisation.
Also I had to retrigger the webhook on github side.

**Pull request merged**
