### PR TITLE
Added rest-api-tests.

### PR DESCRIPTION
**Pull request by fulmicoton**
This PR does not add them to CI yet.

See README.md

### CODE REVIEW

**Comment by fulmicoton** [comment]
@evanxg852000 can you review?

**Comment by guilload** [comment]
Does it have to live at the root of the repo?

**Comment by fulmicoton** [comment]
Not really no. I put it there because quickwit/ contains more items than /. 
@guilload  Any strong opinion here?

**Comment by guilload** [comment]
Not really. I just want to avoid cluttering the root of the project again. Personally, I'd put this in `/tests/rest-api-tests` or `quickwit/tests/rest-api-tests`.

**Comment by fulmicoton** [comment]
I moved it to quickwit/rest-api-tests...
We can create a parent `tests/` directory when we have more stuff to put it in.

**Review by evanxg852000 — APPROVED** [review]
LGTM, just had a few small suggestions.

**Pull request merged**
